# Validate both title and commits, only commits, only title, or any commit?
commitsOnly: true
# Allow use of default (unsemantic) Merge commits?
allowMergeCommits: false
# Allow use of default (unsemantic) Revert commits?
allowRevertCommits: false
