# Always validate the PR title AND all the commits
titleAndCommits: true
# Don't allow unsemantic merge commits
allowMergeCommits: false
# Allow use of Revert commits (eg on github: "Revert "feat: ride unicorns"")
# this is only relevant when using commitsOnly: true (or titleAndCommits: true)
allowRevertCommits: true
