tabWidth: 4
useTabs: true
singleQuote: true
quoteProps: 'consistent'
jsxSingleQuote: true
trailingComma: 'es5'
jsxBracketSameLine: true
printWidth: 100
svelteStrictMode: true
svelteSortOrder: scripts-styles-markup
svelteAllowShorthand: true
svelteBracketNewLine: false
