name: Automatic Pull Request on branch push
on:
  push
jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: create-pr
        uses: "smartinspereira/auto-create-pr-action@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          BRANCH_PREFIX: "issue-"
          BASE_BRANCH: "master"
          PULL_REQUEST_BODY: "This PR was created automatically in response to pushing to an issue branch. Please edit it or add additional information as a comment."
          PULL_REQUEST_TITLE: "feat: Resolve Issue"
          PULL_REQUEST_DRAFT: true
