name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'That was your very first issue ※\(^o^)/※'
        pr-message: 'Wow, you contributed your first PR! You deserve a hug (づ｡◕‿‿◕｡)づ'
