name: On reviewer approval
on:
  pull_request:
    types:
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  execute:
    name: Rebase and Merge automatically
    runs-on: ubuntu-latest
    steps:
      - name: Automatically rebase and merge anything with the approved label
        uses: "pascalgn/automerge-action@f81beb99aef41bb55ad072857d43073fba833a98"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: Approved
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_FORKS: false
          MERGE_RETRIES: 3
          MERGE_RETRY_SLEEP: 10000
          MERGE_DELETE_BRANCH: true
          UPDATE_LABELS: Approved
          UPDATE_METHOD: rebase
          UPDATE_RETRIES: 3
          UPDATE_RETRY_SLEEP: 10000
