name: On push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  execute:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the current repository
       uses: actions/checkout@master
       with:
         fetch-depth: 0
     - name: Automatically label any merge conflict
       if: github.event_name == 'push'
       uses: mschilde/auto-label-merge-conflicts@master
       with:
         CONFLICT_LABEL_NAME: "merge conflict"
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     - name: Enforce our branching convention
       if: github.event_name == 'pull_request'
       uses: deepakputhraya/action-branch-name@master
       with:
         regex: '(?:all\-contributors\/|issue\-(?:[0-9])+\-|hotfix(?:\-)?)(?:[a-zA-Z0-9_-])+'
         allowed_prefixes: 'issue,all-contributors,hotfix'
         ignore: master
         min_length: 7
         max_length: 100
#     - name: Automatically rebase and merge the PR
#       if: github.event_name == 'pull_request'
#       uses: "pascalgn/automerge-action@f81beb99aef41bb55ad072857d43073fba833a98"
#       env:
#         GITHUB_TOKEN: "${{ secrets.PAT }}"
#         MERGE_LABELS: ''
#         MERGE_COMMIT_MESSAGE: pull-request-title
#         MERGE_FORKS: false
#         MERGE_RETRIES: 3
#         MERGE_RETRY_SLEEP: 10000
#         MERGE_DELETE_BRANCH: true
#         UPDATE_LABELS: ''
#         UPDATE_METHOD: rebase
#         UPDATE_RETRIES: 3
#         UPDATE_RETRY_SLEEP: 10000
#     - name: Automatically bump masters tag version
#       uses: mathieudutour/github-tag-action@v4.5
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         default_bump: false
#         tag_prefix: v
#         release_branches: master
#         create_annotated_tag: false
#         dry_run: false
