name: On push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  execute:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the current repository
       uses: actions/checkout@master
       with:
         fetch-depth: 0
     - name: Automatically label any merge conflict
       uses: mschilde/auto-label-merge-conflicts@master
       if: github.event_name == 'pull_request'
       with:
         CONFLICT_LABEL_NAME: "merge conflict"
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     - name: Enforce our branching convention
       if: github.event_name == 'pull_request'
       uses: deepakputhraya/action-branch-name@master
       with:
         regex: '(?:all\-contributors\/|issue\-(?:[0-9])+\-)(?:[a-zA-Z0-9_-])+'
         allowed_prefixes: 'issue,all-contributors'
         ignore: master
         min_length: 7
         max_length: 100
#     - name: Automatically bump masters tag version
#       uses: mathieudutour/github-tag-action@v4.5
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         default_bump: false
#         tag_prefix: v
#         release_branches: master
#         create_annotated_tag: false
#         dry_run: false
