name: Pull request or issue created
on:
    pull_request:
        types:
            - opened
    issues:
        types:
            - opened
jobs:
    execute:
        name: Onboard, welcome and assign
        runs-on: ubuntu-latest
        steps:
            - name: Add new issues to the To do column
              if: github.event_name == 'issues'
              uses: alex-page/github-project-automation-plus@v0.2.4
              with:
                  project: Board
                  column: To do
                  repo-token: '${{ secrets.PAT }}'
            - name: Add new pull requests to the In progress column
              if: github.event_name == 'pull_request'
              uses: alex-page/github-project-automation-plus@v0.2.4
              with:
                  project: Board
                  column: In progress
                  repo-token: '${{ secrets.PAT }}'
            - uses: hmarr/auto-approve-action@v2.0.0
              if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'allcontributors[bot]'
              with:
                  github-token: '${{ secrets.PAT }}'
