name: Pull request or issue created
on:
    pull_request:
        types:
            - opened
    issues:
        types:
            - opened
jobs:
    execute:
        name: Check and add to project board
        runs-on: ubuntu-latest
        steps:
            - name: Assign author
              if: github.event_name == 'pull_request'
              uses: technote-space/assign-author@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
            - name: Add new issues to the To do column
              if: github.event_name == 'issues'
              uses: alex-page/github-project-automation-plus@v0.2.4
              with:
                  project: Board
                  column: To do
                  repo-token: ${{ secrets.PAT }}
            - name: Add new pull requests to the In progress column
              if: github.event_name == 'pull_request'
              uses: alex-page/github-project-automation-plus@v0.2.4
              with:
                  project: Board
                  column: In progress
                  repo-token: ${{ secrets.PAT }}
            - name: Welcome first-time contributors
              uses: actions/first-interaction@v1
              with:
                  repo-token: ${{ secrets.PAT }}
                  issue-message: 'Hi! Please familiarize yourself with our Contribution guide (Contributing.md) in the root of this repository. Thanks for contributing.'
                  pr-message: "It's me again. Don't forget to mark your PR as 'ready for review' within a couple days!"
