name: Automatic Revert

on:
  issue_comment:
    types:
      - created

jobs:
    executed:
        name: Automatic Revert
        runs-on: ubuntu-latest
        if: contains(github.event.comment.body, '/revert')
        steps:
          - name: Checkout latest code
            uses: actions/checkout@v2
          - name: Automatic Revert
            uses: srt32/revert@v0.0.1
            env:
                GITHUB_TOKEN: ${{ secrets.PAT }}
