name: Pull request is ready for review
on:
    pull_request:
        types:
            - ready_for_review
			- review_requested
			- review_request_removed
jobs:
    execute:
        name: Toggle the 'ready for review' label
        runs-on: ubuntu-latest
        steps:
		  - name: label swapping
            uses: jinmayamashita/ready-for-review@1.0.0
            with:
                in-progress-label: 'in progress'
                ready-for-review-label: 'ready for review'
                repo-token: ${{ secrets.PAT }}
