name: Verify the existance of a linked issue
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  check_run: 
 
jobs:
  verify:
    runs-on: ubuntu-latest
    name: Ensure Pull Request has a linked issue
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: "I wasn't able to find a linked issue. Please link one by mentioning it in the body of your PR."
